# Generated by Django 4.2.5 on 2023-09-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='char_name',
            field=models.CharField(default='Bonaparte', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='role',
            field=models.CharField(default='Stealth Assasin', max_length=255),
        ),
    ]
